var GAME_LEVELS = [
  ["                                                                                                                  ",
   "                                                                                                                  ",
   "                                             y                                                                    ",
   "                                            xxx                                                                   ",
   "                                                                                                                  ",
   "                                                                                                                  ",
   "                                                                                                                  ",
   "                                                           y                                                      ",
   "                                                          xxx                                        y            ",
   "                                  y                       x  x                                       x            ",
   "                                 xxx                  x   xxx          xx                 x     x   x x           ",
   "                                 xx              x   x x  x  x        x              x     x   x   xxxxx          ",
   "  xx                       x  x  xxx       x    x x   x   x  x         x            x x     x x   x     x         ",
   "  x                 xxxxx  xxxx       xxxx x     x             xxxxx    x    x     xxxxx     x                    ",
   "  x            y      x    x  x       xx   xxxx                  x    xx     x    x     x                         ",
   "  x          xxxx     x               x                        xxxxx         xxxx                             o   ",
   "  x    @     x  x                                                                                            xxx  ",
   "  xxxxxxxxxxxx  x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "                                                                                                                  ",
   "                                                                                                                  ",
   "                                                                                                                  ",
   "                                                                                                                  ",
   "                                                                                                                  ",
   "                                                                                                                 "],
  ["                                      x!!x                                                                        ",
   "                                      x!!x?                                                                       ",
   "                                      x!!xxxxxxxxxx                                                               ",
   "                                      xx!!!!!!!!!!xx                                                              ",
   "                                       xxxxxxxxxx!!x                                                              ",
   "                                                xx!x                                                              ",
   "                                                 x!x                                                              ",
   "                                                 xvx                                                              ",
   "                                                                                                                  ",
   "                                                                                                                  ",
   "                                                                                                                  ",
   "                                                                                                                  ",
   "                                                                                                                  ",
   "                                                                                                                  ",
   "                                                                                                                  ",
   "                                                                                                                  ",
   "                                                                                                               xxx",
   "   xx          xxxxxxx        xxx   xxx        x    x                                      xxxxxxxxxxxxxxxxxxxx   ",
   "   x          xx     xx         x   x          x    x                        xxxxxxxxxxxxxx   =      =   |       y",
   "   x         xx       xx        x   x          x    x                   xxxxxx          =         =           =  x",
   "   x  @      x         x        x   x          x    xxxxxxxxxxxxxxxxxxxx             |     =     =  =   x         ",
   "   x xxx     x         x        x   xxxxxxxxxxxx    x                         =  |     =      xx   =    |       = ",
   "    x x      x         x       xx            =           |     =     |    |     =      xxx |        =       =   | ",
   "  o x x      x         x!!!!!!xx          |                       |   =    =       =          =     |    =        ",
   "    x x      x         x!!!!!xx =              =            =       =      xxxxxx     = |  =    =   =   =   |  =  ",
   "    x x      x         x!!!!!x         =            xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "    x x      x         x!!!!!x   |      |     =    xx!!!!!!xx  !                     xxxxxxx                      ",
   "!!!!x x!!!!!!x         x!!!!!xx       xxxxxxxxxxxxxx!!!!!!xx   !                                                  ",
   "!!!!x x!!!!!!x         x!!!!!!xxxxxxxxx!!!!!!!!!!!!!!!!!!xx    !                                                  ",
   "!!!!x x!!!!!!x         x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xx     !                                                  "],
   ["                                                                                                                  ",
    "                                                                                                                  ",
    "                                             y                                                                    ",
    "                                            xxx                                                               =   ",
    "                                              x   |                                                               ",
    "                                              x         xxx                                =                      ",
    "                                              x    =                         y                                    ",
    "                                              x                 |        |   x       =                            ",
    "     ?                x                       x    =                                                              ",
    "    xxxx                   x         xx       x                      xx         =                                 ",
    "            x   x              x              x         =        x                                                ",
    "                                              x     |      xx                 =        |                          ",
    "                                              x                  =                         y                      ",
    "                                              x    xxxx                                xxxxxxxxxx                 ",
    "                  !!!!!!!!v!!!!!!!!v!!!!!v!!!!!v!!!!!!!!v!!!!!v!!!!!!!!v!!!!!v!!!!!!!!v!!!!!v!!!!!!!!!v!!!!!!!v!!!",
    "                                                                                                                  ",
    "                                                                                                                  ",
    "                                                                                                                  ",
    "                                                                                                                  ",
    "  xx                                                                                                              ",
    "  x                                                                                                               ",
    "  x                   y                                                                                   o       ",
    "  x          xxxx     x               x                  x     xxxxx         xxxx                y       xxxx     ",
    "  x    @     x  x            xx              xxxxxxx                     x             xx       xxx               ",
    "  xxxxxxxxxxxx  x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
    "                                                                                                                  ",
    "                                                                                                                  ",
    "                                                                                                                  ",
    "                                                                                                                  ",
    "                                                                                                                  ",
    "                                                                                                                 "],

];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
